# Generated by Django 2.1.1 on 2020-01-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='description',
            field=models.TextField(blank=True, default='Hello'),
        ),
    ]
